export { AlimentosService } from './services/alimentos.service';
export { AutenticationService } from './services/autentication.service';
export { DietaAlimentosService } from './services/dieta-alimentos.service';
export { DietasService } from './services/dietas.service';
export { DificultadesService } from './services/dificultades.service';
export { EjerciciosService } from './services/ejercicios.service';
export { RecoveryPasswordService } from './services/recovery-password.service';
export { RutinasService } from './services/rutinas.service';
export { UserService } from './services/user.service';
